name: readme_sthlp

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - 'calipmatch.sthlp'
  workflow_dispatch:

jobs:
  readme_sthlp:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # change max time from default 6hr

    steps:
      - name: Install Stata
        run: |
          # Install Stata
          mkdir -p /tmp/statafiles
          curl -u oi:${OI_HTTPS_PW} https://d2bx6aas1fcmzl.cloudfront.net/stata16/Stata16Linux64.tar.gz --output /tmp/statafiles/Stata16Linux64.tar.gz
          cd /tmp/statafiles
          tar -zxf ./Stata16Linux64.tar.gz
          sudo mkdir -p /usr/local/stata16
          cd /usr/local/stata16

          # The following command returns 1 even though it's ok
          set +e
          sudo sh -c 'yes | /tmp/statafiles/install'
          set -e

          cd /usr/local/bin
          sudo ln -s /usr/local/stata16/stata-mp .
          sudo ln -s /usr/local/stata16/xstata-mp .
          sudo curl -u oi:${OI_HTTPS_PW} https://d2bx6aas1fcmzl.cloudfront.net/stata16/stata.lic --output /usr/local/stata16/stata.lic
          rm -r /tmp/statafiles
          cd /tmp
        env:
          OI_HTTPS_PW: ${{ secrets.OI_HTTPS_PW }}

      - name: Check out code repository (main branch)
        uses: actions/checkout@v2
        if: github.ref == 'refs/heads/main'

      - name: Check out code repository (PR branch)
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
        if: github.ref != 'refs/heads/main'

      - name: Convert Stata help file to HTML
        run: stata-mp log html calipmatch.sthlp calipmatch.html

      - name: Place Stata help file in README.md
        run: |
          sed -z -i 's/<!-- Begin calipmatch.sthlp -->.*<!-- End calipmatch.sthlp -->/<!-- Begin calipmatch.sthlp -->\n\n<!-- End calipmatch.sthlp -->/' README.md
          sed -i '/<!-- Begin calipmatch.sthlp -->/ r calipmatch.html' README.md
          rm calipmatch.html

      - name: Check if there are changes
        run: |
          set +e
          test -z "$(git status --porcelain)"
          echo "README_UPDATED=$?" >> $GITHUB_ENV

      - name: Push updated README to Github
        run: |
          git config user.name OppInsights-Bot
          git config user.email info@opportunityinsights.org
          git add README.md
          git commit -m "README: update embedded calipmatch.sthlp"
          git push
        if: env.README_UPDATED == 1
