name: stata_tests

on:
  workflow_dispatch:

jobs:
  stata_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # change max time from default 6hr

    steps:
      - name: Hello World
        run: echo "Hello World"
